version: '2'
services:

  nginx:
    # build from Dockerfile
    build:
      # path will be used in Dockerfile
      context: .
      # location of Dockerfile
      dockerfile: ./nginx/build/Dockerfile
    # Dockerfileで設定したimage
    image: nginx
    container_name: jo-nginx
    ports:
      # macで接続するport / dockerが開いているport
      - 8080:80
    volumes:
      # localのパス / コンテナ内のパス
      - ./app/public:/usr/share/nginx/html
